name: dataanalysis_clean
channels:
  - conda-forge
  - defaults
dependencies:
  - _openmp_mutex=4.5
  - altair=6.0.0
  - anyio=4.12.0
  - aom=3.9.1
  - appnope=0.1.4
  - argon2-cffi=25.1.0
  - argon2-cffi-bindings=25.1.0
  - arrow=1.4.0
  - asttokens=3.0.1
  - async-lru=2.0.5
  - attrs=25.4.0
  - babel=2.17.0
  - beautifulsoup4=4.14.3
  - bleach=6.3.0
  - bleach-with-css=6.3.0
  - blosc=1.21.6
  - branca=0.8.2
  - brotli=1.2.0
  - brotli-bin=1.2.0
  - brotli-python=1.2.0
  - bzip2=1.0.8
  - c-ares=1.34.5
  - ca-certificates=2025.11.12
  - cached-property=1.5.2
  - cached_property=1.5.2
  - cairo=1.16.0
  - catboost=1.2.8
  - certifi=2025.11.12
  - cffi=1.17.1
  - charset-normalizer=3.4.4
  - comm=0.2.3
  - contourpy=1.3.1
  - cssselect2=0.8.0
  - cycler=0.12.1
  - dav1d=1.2.1
  - debugpy=1.8.17
  - decorator=5.2.1
  - defusedxml=0.7.1
  - et_xmlfile=2.0.0
  - exceptiongroup=1.3.1
  - executing=2.2.1
  - expat=2.7.1
  - folium=0.20.0
  - font-ttf-dejavu-sans-mono=2.37
  - font-ttf-inconsolata=3.000
  - font-ttf-source-code-pro=2.038
  - font-ttf-ubuntu=0.83
  - fontconfig=2.14.1
  - fonts-conda-ecosystem=1
  - fonts-conda-forge=1
  - fonttools=4.61.0
  - fqdn=1.5.1
  - freetype=2.13.3
  - freexl=2.0.0
  - fribidi=1.0.16
  - gdk-pixbuf=2.42.10
  - geopandas=1.1.1
  - geopandas-base=1.1.1
  - geos=3.10.6
  - geotiff=1.7.0
  - gettext=0.25.1
  - gettext-tools=0.25.1
  - giflib=5.2.2
  - glib=2.84.2
  - glib-tools=2.84.2
  - graphite2=1.3.14
  - graphviz=2.50.0
  - gts=0.7.6
  - h11=0.16.0
  - h2=4.3.0
  - harfbuzz=10.2.0
  - hpack=4.1.0
  - httpcore=1.0.9
  - httpx=0.28.1
  - hyperframe=6.1.0
  - icu=73.2
  - idna=3.11
  - importlib-metadata=8.7.0
  - ipykernel=7.1.0
  - ipython=8.37.0
  - isoduration=20.11.0
  - jedi=0.19.2
  - jinja2=3.1.6
  - joblib=1.5.2
  - jpeg=9e
  - json-c=0.16
  - json5=0.12.1
  - jsonpointer=3.0.0
  - jsonschema=4.25.1
  - jsonschema-specifications=2025.9.1
  - jsonschema-with-format-nongpl=4.25.1
  - jupyter-lsp=2.3.0
  - jupyter_client=8.6.3
  - jupyter_core=5.9.1
  - jupyter_events=0.12.0
  - jupyter_server=2.17.0
  - jupyter_server_terminals=0.5.3
  - jupyterlab=4.5.0
  - jupyterlab_pygments=0.3.0
  - jupyterlab_server=2.28.0
  - khronos-opencl-icd-loader=2024.10.24
  - kiwisolver=1.4.9
  - krb5=1.21.3
  - lark=1.3.1
  - lcms2=2.16
  - lerc=4.0.0
  - libarchive=3.7.7
  - libasprintf=0.25.1
  - libasprintf-devel=0.25.1
  - libavif=1.3.0
  - libavif16=1.3.0
  - libblas=3.11.0
  - libboost=1.88.0
  - libbrotlicommon=1.2.0
  - libbrotlidec=1.2.0
  - libbrotlienc=1.2.0
  - libcblas=3.11.0
  - libcurl=8.14.1
  - libcxx=19.1.7
  - libdeflate=1.22
  - libedit=3.1.20250104
  - libev=4.33
  - libffi=3.4.4
  - libgcc=15.2.0
  - libgd=2.3.3
  - libgdal-core=3.11.0
  - libgettextpo=0.25.1
  - libgettextpo-devel=0.25.1
  - libgfortran=15.2.0
  - libgfortran5=15.2.0
  - libglib=2.84.2
  - libiconv=1.18
  - libintl=0.25.1
  - libintl-devel=0.25.1
  - libkml=1.3.0
  - liblapack=3.11.0
  - liblightgbm=4.6.0
  - libltdl=2.4.3a
  - libnghttp2=1.57.0
  - libopenblas=0.3.30
  - libpng=1.6.39
  - librsvg=2.56.3
  - libsodium=1.0.20
  - libspatialite=5.1.0
  - libssh2=1.11.1
  - libtiff=4.7.0
  - libtool=2.5.4
  - libwebp=1.3.2
  - libwebp-base=1.3.2
  - libxgboost=3.1.2
  - libxml2=2.13.8
  - lightgbm=4.6.0
  - llvm-openmp=19.1.7
  - lz4-c=1.9.4
  - mapclassify=2.6.1
  - markupsafe=3.0.3
  - matplotlib=3.9.4
  - matplotlib-base=3.9.4
  - matplotlib-inline=0.2.1
  - minizip=4.0.3
  - mistune=3.1.4
  - munkres=1.1.4
  - narwhals=2.12.0
  - nbclient=0.10.2
  - nbconvert-core=7.16.6
  - nbformat=5.10.4
  - ncurses=6.5
  - nest-asyncio=1.6.0
  - networkx=3.4.2
  - notebook-shim=0.2.4
  - numpy=2.2.6
  - opencl-headers=2025.06.13
  - openjpeg=2.5.2
  - openpyxl=3.1.5
  - openssl=3.6.0
  - overrides=7.7.0
  - packaging=25.0
  - pandas=2.3.3
  - pandocfilters=1.5.0
  - pango=1.50.7
  - parso=0.8.5
  - patsy=1.0.2
  - pcre2=10.42
  - pexpect=4.9.0
  - pickleshare=0.7.5
  - pillow=11.3.0
  - pip=25.3
  - pixman=0.46.4
  - platformdirs=4.5.0
  - plotly=6.5.0
  - proj=9.3.1
  - prometheus_client=0.23.1
  - prompt-toolkit=3.0.52
  - psutil=7.1.3
  - ptyprocess=0.7.0
  - pure_eval=0.2.3
  - py-xgboost=3.1.2
  - pycparser=2.22
  - pydyf=0.11.0
  - pygments=2.19.2
  - pyogrio=0.10.0
  - pyparsing=3.2.5
  - pyphen=0.17.2
  - pyproj=3.6.1
  - pysocks=1.7.1
  - python=3.10.18
  - python-dateutil=2.9.0.post0
  - python-dotenv=1.2.1
  - python-fastjsonschema=2.21.2
  - python-graphviz=0.21
  - python-json-logger=2.0.7
  - python-tzdata=2025.2
  - python_abi=3.10
  - pytz=2025.2
  - pyyaml=6.0.3
  - pyzmq=27.1.0
  - qhull=2020.2
  - rav1e=0.7.1
  - readline=8.3
  - referencing=0.37.0
  - requests=2.32.5
  - rfc3339-validator=0.1.4
  - rfc3986-validator=0.1.1
  - rfc3987-syntax=1.1.0
  - rpds-py=0.30.0
  - scikit-learn=1.7.2
  - scipy=1.15.2
  - seaborn=0.13.2
  - seaborn-base=0.13.2
  - send2trash=1.8.2
  - setuptools=78.1.1
  - shapely=2.1.1
  - six=1.17.0
  - sniffio=1.3.1
  - soupsieve=2.8
  - sqlite=3.50.2
  - stack_data=0.6.3
  - statsmodels=0.14.5
  - svt-av1=3.1.2
  - tabulate=0.9.0
  - terminado=0.18.1
  - threadpoolctl=3.6.0
  - tinycss2=1.5.0
  - tinyhtml5=2.0.0
  - tk=8.6.15
  - tomli=2.3.0
  - tornado=6.5.2
  - traitlets=5.14.3
  - typing-extensions=4.15.0
  - typing_extensions=4.15.0
  - typing_utils=0.1.0
  - tzdata=2025b
  - unicodedata2=17.0.0
  - uri-template=1.3.0
  - uriparser=0.9.8
  - urllib3=2.2.1
  - wcwidth=0.2.14
  - weasyprint=66.0
  - webcolors=25.10.0
  - webencodings=0.5.1
  - websocket-client=1.9.0
  - wheel=0.45.1
  - xerces-c=3.2.5
  - xgboost=3.1.2
  - xyzservices=2025.11.0
  - xz=5.6.4
  - yaml=0.2.5
  - zeromq=4.3.5
  - zipp=3.23.0
  - zlib=1.2.13
  - zstd=1.5.6

